spring:
  application:
    name: Projet_Java_DevManager
  datasource:
    url: jdbc:mysql://localhost:3306/devmanagerdb
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver

